In [3]:
import torch

In [4]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [5]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
x.shape

torch.Size([2, 5])

In [9]:
y = torch.rand([2,5])
y

tensor([[0.0389, 0.1239, 0.4300, 0.2072, 0.2277],
        [0.4609, 0.2448, 0.6770, 0.8441, 0.0385]])

In [12]:
y.view([1,10]) #to reshape
y

tensor([[0.0389, 0.1239, 0.4300, 0.2072, 0.2277],
        [0.4609, 0.2448, 0.6770, 0.8441, 0.0385]])

In [14]:
y = y.view([1,10]) # need to reassign
y

tensor([[0.0389, 0.1239, 0.4300, 0.2072, 0.2277, 0.4609, 0.2448, 0.6770, 0.8441,
         0.0385]])